import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
         <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
             target="_blank"
             rel="noopener noreferrer"
           >
           By{' '}
              <Image
                src="/vercel.svg"
               alt="Vercel Logo"
               className={styles.vercelLogo}
                width={100}
                height={24}/>
           </a>
          </div>
       
	  <div className={styles.center}>
	  	<h2>Did you complete the daily puzzle?</h2>  
	  </div>
	  
        <div className={styles.grid}>
          <a
            href="https://www.nytimes.com/games/wordle/index.html"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Wordle <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Get 6 chances to guess a 5-letter word.
            </p>
          </a>

          <a
            href="https://www.nytimes.com/puzzles/sudoku"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Sudoku <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Try this numbers game, minus the math!
            </p>
          </a>

          <a
            href="https://www.nytimes.com/puzzles/spelling-bee"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Spelling Bee <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              How many words can you make with 7 letters?
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
